using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Database;
using Database.Entities;
using Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace GUI.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class DeviceController : ControllerBase
    {
        private  ILogger<HomeController> Logger { get; set; }
        private IConfiguration Configuration { get; set; }
        private CompleteGPSUtilityContext Context { get; set; }

        public DeviceController(ILogger<HomeController> logger, IConfiguration configuration, CompleteGPSUtilityContext context)
        {
            Logger = logger;
            Configuration = configuration;
            Context = context;
        }

        [HttpPost]
        public async Task<IActionResult> UpdateLocations(ProbeDataModel model)
        {
            Device device = await Context.Devices.FirstOrDefaultAsync(dev => dev.IMEI == model.k);

            if (device == null)
            {
                if (Parser.Bool(Configuration["Api:NewIMEIAllowed"]))
                {
                    device = new Device
                    {
                        IMEI = model.k,
                        Name = "AutoGenerated",
                    };
                    Context.Devices.Add(device);

                    if ((await Context.SaveChangesAsync()) <= 0)
                    {
                        Logger.LogError($"Cannot insert new device into database");
                    }
                    else
                    {
                        Logger.LogInformation($"Created new Device with IMEI: [{device.IMEI}]");
                    }
                }
                else
                {
                    return BadRequest("Unauthorized");
                }
            }

            if (model.l.Count == 0)
            {
                Logger.LogWarning($"Locations list is empty.");
                return BadRequest("Locations empty");
            }
            else
            {
                foreach (var modelLocation in model.l)
                {
                    Location location = new Location
                    {
                        Latitude = modelLocation.a,
                        Longitude = modelLocation.o,
                        Altitude = modelLocation.l.HasValue ? modelLocation.l.Value : (short)-1,
                        BatteryPercentage = model.p,
                        BatteryVoltage = model.v,
                        Device = device,
                        DeviceId = device.DeviceId,
                        TimeUnix = modelLocation.y,
                    };

                    Context.Locations.Add(location);
                    if ((await Context.SaveChangesAsync()) <= 0)
                    {
                        string json = JsonConvert.SerializeObject(location, Formatting.Indented);
                        Logger.LogError($"Cannot insert new Location into database.\r\nJSON:{json}");
                    }
                    else
                    {
                        Logger.LogDebug($"Inserted new Location for IMEI: [{device.IMEI}]");
                    }
                }
            }

            return Ok();
         
           
        }
    }
}